### ISSUE TITLE
user.shell: ls: internal implementation doesn't do globbing or options

### ISSUE THREAD

**Issue by hishamhm** [hishamhm/userland#2]
The internal `user.shell` implementation of `ls` is fun and all, since it uses inotify to auto-refresh when the contents of the folder change, but it currently lacks support for globbing (`ls *.c`) or options (`ls -l`, etc.)

I guess what I'd really like is porting our [ls-replacement](https://github.com/gobolinux/Scripts/blob/master/src/List.c) from GoboLinux :)

**Comment by Superpat** [comment]
Are you sure you want to add that kind of functionality to every internal command ? I feel using something like [entr(1)](http://eradman.com/entrproject/) at the first step of your data flow would be better.

**Comment by hishamhm** [comment]
I've been treating `ls` as a little special thing because it is a "view into the filesystem". What I've been thinking really is that what I want is a sort of "file-manager" cell that presents this view of the filesystem in a more interactive way. It can look like `ls` at first but provide fs navigation, operations, etc.

**Comment by hishamhm** [comment]
What I ended up doing in the meantime was to switch back to standard ls whenever _any_ option is given. I'll eventually pop the custom ls out of the "shell" mode into its own file manager cell. So technically, this "shell ls doesn't handle globbing" issue is "solved" for now.

**Comment by Superpat** [comment]
As a file manager, handling it's file watching does make more sense.
