### ISSUE TITLE
Failure to install inotify dependency on Ubuntu (with solution)

### ISSUE THREAD

**Issue by ghost** [hishamhm/userland#3]
Just dropping this here as I've just encountered and solved this, so it should be documented for someone else sharing the problem.

During install I got this:
```
Installing https://luarocks.org/inotify-0.5-1.rockspec

Error: Failed installing dependency: https://luarocks.org/inotify-0.5-1.rockspec - Could not find header file for INOTIFY
  No file sys/inotify.h in /usr/local/include
  No file sys/inotify.h in /usr/include
  No file sys/inotify.h in /include
You may have to install INOTIFY in your system and/or pass INOTIFY_DIR or INOTIFY_INCDIR to the luarocks command.
Example: luarocks install inotify INOTIFY_DIR=/usr/local
```

..for some reason `luarocks` was not looking everywhere for that critical `/sys` directory, it turns out these days it's to be found at `/usr/include/x86_64-linux-gnu`. So, I was able to manually install the inotify lib with this line:

`$ luarocks --lua-version 5.1 --local install inotify INOTIFY_INCDIR=/usr/include/x86_64-linux-gnu`

Why did I encounter this issue? Not clear. I am running fairly stock Ubuntu. I installed Love from the official stable PPA, and luarocks according to the Github wiki for luarocks. To install luarocks, I also installed lua5.1 from the Ubuntu repos. So, somewhere between Ubuntu lua and 'wild' Luarocks, perhaps there is disagreement on `LD_LIBRARY_PATH` or something. Hopefully this is not a commonplace bug.

**Comment by gilletteonmeheleparim** [comment]
what would be the equivalent directory for MacOS?
